package com.model;

import java.io.Serializable;

/**
 * Model class of address.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class Address implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** addressid. */
	private Integer addressid;

	/** userid. */
	private Integer userid;

	/** economize. */
	private String economize;

	/** market. */
	private String market;

	/** county. */
	private String county;

	/** detailed. */
	private String detailed;

	/**
	 * Constructor.
	 */
	public Address() {
	}

	/**
	 * Set the addressid.
	 * 
	 * @param addressid
	 *            addressid
	 */
	public void setAddressid(Integer addressid) {
		this.addressid = addressid;
	}

	/**
	 * Get the addressid.
	 * 
	 * @return addressid
	 */
	public Integer getAddressid() {
		return this.addressid;
	}

	/**
	 * Set the userid.
	 * 
	 * @param userid
	 *            userid
	 */
	public void setUserid(Integer userid) {
		this.userid = userid;
	}

	/**
	 * Get the userid.
	 * 
	 * @return userid
	 */
	public Integer getUserid() {
		return this.userid;
	}

	/**
	 * Set the economize.
	 * 
	 * @param economize
	 *            economize
	 */
	public void setEconomize(String economize) {
		this.economize = economize;
	}

	/**
	 * Get the economize.
	 * 
	 * @return economize
	 */
	public String getEconomize() {
		return this.economize;
	}

	/**
	 * Set the market.
	 * 
	 * @param market
	 *            market
	 */
	public void setMarket(String market) {
		this.market = market;
	}

	/**
	 * Get the market.
	 * 
	 * @return market
	 */
	public String getMarket() {
		return this.market;
	}

	/**
	 * Set the county.
	 * 
	 * @param county
	 *            county
	 */
	public void setCounty(String county) {
		this.county = county;
	}

	/**
	 * Get the county.
	 * 
	 * @return county
	 */
	public String getCounty() {
		return this.county;
	}

	/**
	 * Set the detailed.
	 * 
	 * @param detailed
	 *            detailed
	 */
	public void setDetailed(String detailed) {
		this.detailed = detailed;
	}

	/**
	 * Get the detailed.
	 * 
	 * @return detailed
	 */
	public String getDetailed() {
		return this.detailed;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((addressid == null) ? 0 : addressid.hashCode());
		result = prime * result + ((userid == null) ? 0 : userid.hashCode());
		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		Address other = (Address) obj;
		if (addressid == null) {
			if (other.addressid != null) {
				return false;
			}
		} else if (!addressid.equals(other.addressid)) {
			return false;
		}
		if (userid == null) {
			if (other.userid != null) {
				return false;
			}
		} else if (!userid.equals(other.userid)) {
			return false;
		}
		return true;
	}

}
