package com.model;

import java.io.Serializable;

/**
 * Model class of goods.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */

public class Goods implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;
	/** goodsid. */
	private Integer goodsid;

	/** goodsname. */
	private String goodsname;

	/** price. */
	private Integer price;

	/** stock. */
	private Integer stock;

	/** icon. */
	private String icon;

	/** typeid. */
	private Integer typeid;

	/**
	 * Constructor.
	 */
	public Goods() {
	}

	/**
	 * Set the goodsid.
	 * 
	 * @param goodsid
	 *            goodsid
	 */
	public void setGoodsid(Integer goodsid) {
		this.goodsid = goodsid;
	}

	/**
	 * Get the goodsid.
	 * 
	 * @return goodsid
	 */
	public Integer getGoodsid() {
		return this.goodsid;
	}

	/**
	 * Set the goodsname.
	 * 
	 * @param goodsname
	 *            goodsname
	 */
	public void setGoodsname(String goodsname) {
		this.goodsname = goodsname;
	}

	/**
	 * Get the goodsname.
	 * 
	 * @return goodsname
	 */
	public String getGoodsname() {
		return this.goodsname;
	}

	/**
	 * Set the price.
	 * 
	 * @param price
	 *            price
	 */
	public void setPrice(Integer price) {
		this.price = price;
	}

	/**
	 * Get the price.
	 * 
	 * @return price
	 */
	public Integer getPrice() {
		return this.price;
	}

	/**
	 * Set the stock.
	 * 
	 * @param stock
	 *            stock
	 */
	public void setStock(Integer stock) {
		this.stock = stock;
	}

	/**
	 * Get the stock.
	 * 
	 * @return stock
	 */
	public Integer getStock() {
		return this.stock;
	}

	/**
	 * Set the icon.
	 * 
	 * @param icon
	 *            icon
	 */
	public void setIcon(String icon) {
		this.icon = icon;
	}

	/**
	 * Get the icon.
	 * 
	 * @return icon
	 */
	public String getIcon() {
		return this.icon;
	}

	/**
	 * Set the typeid.
	 * 
	 * @param typeid
	 *            typeid
	 */
	public void setTypeid(Integer typeid) {
		this.typeid = typeid;
	}

	/**
	 * Get the typeid.
	 * 
	 * @return typeid
	 */
	public Integer getTypeid() {
		return this.typeid;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((goodsid == null) ? 0 : goodsid.hashCode());
		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		Goods other = (Goods) obj;
		if (goodsid == null) {
			if (other.goodsid != null) {
				return false;
			}
		} else if (!goodsid.equals(other.goodsid)) {
			return false;
		}
		return true;
	}

}
