package com.model;

import java.io.Serializable;
import java.util.Date;

/**
 * Model class of orders.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class Orders implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** orderid. */
	private Integer orderid;

	/** userid. */
	private Integer userid;

	/** goodsid. */
	private Integer goodsid;

	/** buytime. */
	private Date buytime;

	/** price. */
	private Integer price;

	/** goodsnumber. */
	private Integer goodsnumber;

	/**
	 * Constructor.
	 */
	public Orders() {
	}

	/**
	 * Set the orderid.
	 * 
	 * @param orderid
	 *            orderid
	 */
	public void setOrderid(Integer orderid) {
		this.orderid = orderid;
	}

	/**
	 * Get the orderid.
	 * 
	 * @return orderid
	 */
	public Integer getOrderid() {
		return this.orderid;
	}

	/**
	 * Set the userid.
	 * 
	 * @param userid
	 *            userid
	 */
	public void setUserid(Integer userid) {
		this.userid = userid;
	}

	/**
	 * Get the userid.
	 * 
	 * @return userid
	 */
	public Integer getUserid() {
		return this.userid;
	}

	/**
	 * Set the goodsid.
	 * 
	 * @param goodsid
	 *            goodsid
	 */
	public void setGoodsid(Integer goodsid) {
		this.goodsid = goodsid;
	}

	/**
	 * Get the goodsid.
	 * 
	 * @return goodsid
	 */
	public Integer getGoodsid() {
		return this.goodsid;
	}

	/**
	 * Set the buytime.
	 * 
	 * @param buytime
	 *            buytime
	 */
	public void setBuytime(Date buytime) {
		this.buytime = buytime;
	}

	/**
	 * Get the buytime.
	 * 
	 * @return buytime
	 */
	public Date getBuytime() {
		return this.buytime;
	}

	/**
	 * Set the price.
	 * 
	 * @param price
	 *            price
	 */
	public void setPrice(Integer price) {
		this.price = price;
	}

	/**
	 * Get the price.
	 * 
	 * @return price
	 */
	public Integer getPrice() {
		return this.price;
	}

	/**
	 * Set the goodsnumber.
	 * 
	 * @param goodsnumber
	 *            goodsnumber
	 */
	public void setGoodsnumber(Integer goodsnumber) {
		this.goodsnumber = goodsnumber;
	}

	/**
	 * Get the goodsnumber.
	 * 
	 * @return goodsnumber
	 */
	public Integer getGoodsnumber() {
		return this.goodsnumber;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((orderid == null) ? 0 : orderid.hashCode());
		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		Orders other = (Orders) obj;
		if (orderid == null) {
			if (other.orderid != null) {
				return false;
			}
		} else if (!orderid.equals(other.orderid)) {
			return false;
		}
		return true;
	}

}
