package com.model;

import java.io.Serializable;

/**
 * Model class of user_shop.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class UserShop implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** userid. */
	private Integer userid;

	/** shoppingid. */
	private Integer shoppingid;

	/**
	 * Constructor.
	 */
	public UserShop() {
	}

	/**
	 * Set the userid.
	 * 
	 * @param userid
	 *            userid
	 */
	public void setUserid(Integer userid) {
		this.userid = userid;
	}

	/**
	 * Get the userid.
	 * 
	 * @return userid
	 */
	public Integer getUserid() {
		return this.userid;
	}

	/**
	 * Set the shoppingid.
	 * 
	 * @param shoppingid
	 *            shoppingid
	 */
	public void setShoppingid(Integer shoppingid) {
		this.shoppingid = shoppingid;
	}

	/**
	 * Get the shoppingid.
	 * 
	 * @return shoppingid
	 */
	public Integer getShoppingid() {
		return this.shoppingid;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((userid == null) ? 0 : userid.hashCode());
		result = prime * result + ((shoppingid == null) ? 0 : shoppingid.hashCode());
		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		UserShop other = (UserShop) obj;
		if (userid == null) {
			if (other.userid != null) {
				return false;
			}
		} else if (!userid.equals(other.userid)) {
			return false;
		}
		if (shoppingid == null) {
			if (other.shoppingid != null) {
				return false;
			}
		} else if (!shoppingid.equals(other.shoppingid)) {
			return false;
		}
		return true;
	}

}
